# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP_Cache',
            fields=[
                ('ip_cache_no', models.CharField(max_length=16)),
                ('ip', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('cc', models.CharField(max_length=3)),
                ('ip_comment', models.CharField(max_length=500)),
                ('ip_gubun', models.IntegerField(default=0)),
                ('times', models.IntegerField(default=0)),
                ('web_log', models.IntegerField(default=0)),
                ('detect_fw', models.IntegerField(default=0)),
                ('detect_waf', models.IntegerField(default=0)),
                ('detect_ips', models.IntegerField(default=0)),
                ('bl_ibm', models.IntegerField(default=0)),
                ('bl_dg_yn', models.CharField(max_length=3)),
                ('bl_etc', models.CharField(max_length=50)),
                ('block_yn', models.CharField(max_length=3)),
                ('write_time', models.CharField(max_length=20)),
                ('modi_time', models.CharField(max_length=40)),
                ('write_date', models.CharField(max_length=15)),
                ('seq', models.IntegerField(default=0)),
                ('web_ok', models.IntegerField(default=0)),
                ('web_rej', models.IntegerField(default=0)),
                ('fw_pd', models.IntegerField(default=0)),
                ('fw_db', models.IntegerField(default=0)),
                ('waf_ok', models.IntegerField(default=0)),
                ('waf_rej', models.IntegerField(default=0)),
                ('ips_pd', models.IntegerField(default=0)),
                ('ips_db', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Log_full',
            fields=[
                ('log_full_no', models.IntegerField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(max_length=20)),
                ('log_time', models.CharField(max_length=30)),
                ('source_ip', models.CharField(max_length=16)),
                ('dest_ip', models.CharField(max_length=16)),
                ('dest_port', models.CharField(max_length=12)),
                ('result', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=10000)),
                ('get_post', models.CharField(max_length=10)),
                ('raw', models.CharField(max_length=1000)),
                ('attack_code', models.CharField(max_length=500)),
                ('times', models.IntegerField()),
                ('agent', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=500)),
                ('risk_score', models.IntegerField()),
                ('write_time', models.CharField(max_length=20)),
                ('modi_time', models.CharField(max_length=30)),
                ('alarm_yn', models.CharField(max_length=3)),
                ('ip_cache_no', models.CharField(max_length=16)),
                ('attack_cache_no', models.CharField(max_length=16)),
                ('write_date', models.CharField(max_length=12)),
            ],
        ),
    ]
