# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bl',
            fields=[
                ('ip', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('write_time', models.CharField(max_length=20)),
                ('modi_time', models.CharField(max_length=40)),
                ('write_date', models.CharField(max_length=15)),
                ('flag', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='wl',
            fields=[
                ('ip', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('write_time', models.CharField(max_length=20)),
                ('modi_time', models.CharField(max_length=40)),
                ('write_date', models.CharField(max_length=15)),
                ('flag', models.IntegerField(default=0)),
            ],
        ),
    ]
