# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw', '0003_auto_20170512_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_cache',
            name='detect_fw',
        ),
        migrations.RemoveField(
            model_name='ip_cache',
            name='detect_ips',
        ),
        migrations.RemoveField(
            model_name='ip_cache',
            name='detect_waf',
        ),
        migrations.RemoveField(
            model_name='ip_cache',
            name='web_log',
        ),
        migrations.AlterField(
            model_name='bl',
            name='flag',
            field=models.IntegerField(choices=[(1, 'Black List'), (2, 'White List'), (3, 'Holding')], default=1),
        ),
        migrations.AlterField(
            model_name='ip_cache',
            name='bl_dg_yn',
            field=models.IntegerField(default=0),
        ),
    ]
