# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aw', '0004_auto_20170512_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_cache',
            name='detect_fw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ip_cache',
            name='detect_ips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ip_cache',
            name='detect_waf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ip_cache',
            name='web_log',
            field=models.IntegerField(default=0),
        ),
    ]
