# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aw', '0005_auto_20170512_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_cache',
            name='detect_fw',
        ),
        migrations.RemoveField(
            model_name='ip_cache',
            name='detect_ips',
        ),
        migrations.RemoveField(
            model_name='ip_cache',
            name='detect_waf',
        ),
        migrations.RemoveField(
            model_name='ip_cache',
            name='web_log',
        ),
    ]
